FROM node:12-alpine3.12 AS build
# Set working directory
WORKDIR /app
# Copy all files from current directory to working dir in image
COPY package.json ./
# install node modules and build assets
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.19.0-alpine AS prod-stage
# Set working directory to nginx asset directory
COPY --from=build /app/build /usr/share/nginx/html
# Remove default nginx static assets
# Copy static assets from builder stage
# Containers run nginx with global directives and daemon off
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]